swagger: '2.0'
info:
  title: Customer API
  version: 1.0.0
host: us-central1-quiosquefood3000.cloudfunctions.net
schemes:
  - https
securityDefinitions:
  firebase:
    type: oauth2
    authorizationUrl: ""
    flow: implicit
    x-google-issuer: https://securetoken.google.com/quiosquefood3000
    x-google-jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
    x-google-audiences: quiosquefood3000

paths:
  /create-customer:
    post:
      operationId: create-customer
      security:
        - firebase: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - name
              - email
              - cpf
            properties:
              name:
                type: string
              email:
                type: string
              cpf:
                type: string
      responses:
        200:
          description: Success
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
      x-google-backend:
        address: https://us-central1-quiosquefood3000.cloudfunctions.net/create-customer

  /update-customer:
    put:
      operationId: update-customer
      security:
        - firebase: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - cpf
            properties:
              name:
                type: string
              email:
                type: string
              cpf:
                type: string
      responses:
        200:
          description: Success
        401:
          description: Unauthorized
        404:
          description: Customer not found
        500:
          description: Internal Server Error
      x-google-backend:
        address: https://us-central1-quiosquefood3000.cloudfunctions.net/update-customer

  /delete-customer:
    delete:
      operationId: delete-customer
      security:
        - firebase: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - cpf
            properties:
              cpf:
                type: string
      responses:
        200:
          description: Success
        401:
          description: Unauthorized
        404:
          description: Customer not found
        500:
          description: Internal Server Error
      x-google-backend:
        address: https://us-central1-quiosquefood3000.cloudfunctions.net/delete-customer

  /pesquisar-customer:
    get:
      operationId: pesquisar-customer
      security:
        - firebase: []
      parameters:
        - name: cpf
          in: query
          required: true
          type: string
      responses:
        200:
          description: Success
        401:
          description: Unauthorized
        404:
          description: Customer not found
        500:
          description: Internal Server Error
      x-google-backend:
        address: https://us-central1-quiosquefood3000.cloudfunctions.net/pesquisar-customer

security:
  - firebase: []