name: Build and Upload Function Zip

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/package-functions.yml'
  workflow_dispatch:

jobs:
  build-zip:
    runs-on: ubuntu-latest

    env:
      ZIP_NAME: function-source.zip
      BUCKET_NAME: function-bucket-${{ secrets.BUCKET_SUFFIX }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd functions
          npm ci || true  # Ignora se não houver node_modules global

      - name: Create ZIP
        run: |
          cd functions
          zip -r ../${{ env.ZIP_NAME }} .

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload ZIP to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ${{ env.ZIP_NAME }}
          destination: gs://${{ env.BUCKET_NAME }}/${{ env.ZIP_NAME }}

      - name: Output result
        run: echo "Zip uploaded to gs://${{ env.BUCKET_NAME }}/${{ env.ZIP_NAME }}"
