name: Package and Deploy Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT || 'quiosquefood3000' }}
      DATASET_ID: QuiosqueFood
      TABLE_ID: customers
      BUCKET_NAME: function-bucket-quiosquefood

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd functions
          npm ci

      - name: Generate unique ZIP name with timestamp and commit
        id: zip-name
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          COMMIT_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          ZIP_NAME="function-source-${TIMESTAMP}-${COMMIT_SHORT}.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_OUTPUT
          echo "Generated ZIP name: ${ZIP_NAME}"

      - name: Create ZIP package
        run: |
          cd functions
          # Remove any existing ZIP files
          rm -f ../*.zip
          # Create new ZIP with all function files
          zip -r ../${{ steps.zip-name.outputs.ZIP_NAME }} . -x "node_modules/*" "*.git*" "*.DS_Store*"
          
      - name: Verify ZIP contents
        run: |
          echo "ZIP file size:"
          ls -lh ${{ steps.zip-name.outputs.ZIP_NAME }}
          echo "ZIP contents:"
          unzip -l ${{ steps.zip-name.outputs.ZIP_NAME }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Check existing resources
        run: |
          echo "Checking existing resources in GCP:"
          echo "=== Cloud Functions ==="
          gcloud functions list --filter="name:*customer*" || true
          echo "=== PubSub Topics ==="
          gcloud pubsub topics list --filter="name:*customer*" || true
          echo "=== BigQuery Datasets ==="
          bq ls ${{ env.DATASET_ID }} || true
          echo "=== API Gateway APIs ==="
          gcloud api-gateway apis list || true
          echo "=== Storage Buckets ==="
          gsutil ls gs://${{ env.BUCKET_NAME }}/ || true

      - name: Upload new ZIP to Google Cloud Storage
        run: |
          # Remove old ZIP files from bucket
          gsutil -m rm gs://${{ env.BUCKET_NAME }}/function-source*.zip || true
          
          # Upload new ZIP
          gsutil cp ${{ steps.zip-name.outputs.ZIP_NAME }} gs://${{ env.BUCKET_NAME }}/

      - name: Verify ZIP upload
        run: |
          echo "Current bucket contents:"
          gsutil ls -l gs://${{ env.BUCKET_NAME }}/

      - name: Update Terraform variables
        run: |
          cd terraform
          # Create or update terraform.tfvars with new ZIP name
          cat > terraform.tfvars << EOF
          project_id = "${{ env.PROJECT_ID }}"
          region = "us-central1"
          bucket_name = "${{ env.BUCKET_NAME }}"
          zip_object = "${{ steps.zip-name.outputs.ZIP_NAME }}"
          EOF
          
          echo "Terraform variables:"
          cat terraform.tfvars

      - name: Terraform Plan with detailed output
        run: |
          cd terraform
          terraform plan -var-file=terraform.tfvars -detailed-exitcode || {
            exit_code=$?
            if [ $exit_code -eq 2 ]; then
              echo "Changes detected, will apply"
              exit 0
            elif [ $exit_code -eq 1 ]; then
              echo "Terraform plan failed"
              exit 1
            else
              echo "No changes detected"
            fi
          }

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -var-file=terraform.tfvars -auto-approve

      - name: Verify deployment
        run: |
          echo "Listing Cloud Functions:"
          gcloud functions list
          
          echo "Checking PubSub topics:"
          gcloud pubsub topics list
          
          echo "Testing create-customer function (if accessible):"
          gcloud functions describe create-customer || echo "Function not found or not accessible"
